export const CATEGORIES = [
  { name: "Beauty", src: "./img/category/beauty.jpg" },
  { name: "Books", src: "./img/category/books.jpg" },
  { name: "Electronics", src: "./img/category/electronics.jpg" },
  { name: "Fashion", src: "./img/category/fashion.jpg" },
  { name: "Furniture", src: "./img/category/furniture.jpg" },
  { name: "Home & Decor", src: "./img/category/home.jpg" },
  { name: "Pet Supplies", src: "./img/category/pet.jpg" },
  { name: "Sports", src: "./img/category/sports.jpg" },
  { name: "UW Merch", src: "./img/category/uw_merch.jpg" },
  { name: "Others", src: "./img/category/others.jpg" },
];

export const ALL_ITEMS = {
  "-My-j4kWCkj0ZKIcA9tv": {
    category: "Others",
    condition: "Brand new",
    description: "Brand New Ukulele, very nice",
    dropOff: false,
    imgUrls: [
      "https://firebasestorage.googleapis.com/v0/b/dawgo-63d5f.appspot.com/o/itemImages%2Fj4kWCkj0ZKIcA9tv%2Fother.jpg?alt=media&token=cc6a86c0-ef33-4730-802b-5ce3f16e1233",
    ],
    itemId: "-My-j4kWCkj0ZKIcA9tv",
    location: "98105",
    negotiable: true,
    pickUp: true,
    price: "69",
    title: "Ukulele",
    userId: "eN9yXV0gS8deCTlNvNNLJyOjXuJ2",
    savedBy: ["eN9yXV0gS8deCTlNvNNLJyOjXuJ2"],
  },
  "-My-jGgVKzFrDcS7C4Lb": {
    category: "Electronics",
    condition: "used",
    description: "Used for 1 year, good condition.",
    dropOff: true,
    imgUrls: [
      "https://firebasestorage.googleapis.com/v0/b/dawgo-63d5f.appspot.com/o/itemImages%2FjGgVKzFrDcS7C4Lb%2Fiphone.png?alt=media&token=0c0843b5-0ea4-474c-a2ff-ddef5d7e70f5",
    ],
    itemId: "-My-jGgVKzFrDcS7C4Lb",
    location: "98105",
    negotiable: true,
    pickUp: true,
    price: "500",
    title: "iPhone 11 - red",
    userId: "eN9yXV0gS8deCTlNvNNLJyOjXuJ2",
    savedBy: ["eN9yXV0gS8deCTlNvNNLJyOjXuJ2"],
  },
  "-My-ngE6uEDrynDZlImi": {
    category: "Books",
    condition: "used",
    description: "I like big books and I don't know why",
    dropOff: true,
    imgUrls: [
      "https://firebasestorage.googleapis.com/v0/b/dawgo-63d5f.appspot.com/o/itemImages%2FngE6uEDrynDZlImi%2Fbooks.jpg?alt=media&token=9b0cba2b-fa63-4302-aed7-a778c16f4932",
    ],
    itemId: "-My-ngE6uEDrynDZlImi",
    location: "98100",
    negotiable: true,
    pickUp: true,
    price: "30",
    title: "Random Books",
    userId: "eN9yXV0gS8deCTlNvNNLJyOjXuJ2",
    savedBy: ["eN9yXV0gS8deCTlNvNNLJyOjXuJ2"],
  },
  "-My-oD_OGW56f1zMZEFI": {
    category: "Pet Supplies",
    condition: "used",
    description:
      "Half-used pet supplies, selling them because we are moving away.",
    dropOff: false,
    imgUrls: [
      "https://firebasestorage.googleapis.com/v0/b/dawgo-63d5f.appspot.com/o/itemImages%2FoD_OGW56f1zMZEFI%2Fpet%20supplies.jfif?alt=media&token=403a81ed-77ee-449c-b8bf-7078584abf7a",
    ],
    itemId: "-My-oD_OGW56f1zMZEFI",
    location: "98105",
    negotiable: false,
    pickUp: true,
    price: "100",
    title: "Random Pet Supplies",
    userId: "eN9yXV0gS8deCTlNvNNLJyOjXuJ2",
    savedBy: ["eN9yXV0gS8deCTlNvNNLJyOjXuJ2"],
  },
  "-My0Q6wgjfSGBN6Lbsad": {
    category: "Electronics",
    condition: "used",
    description: "1234",
    dropOff: false,
    imgUrls: [
      "https://firebasestorage.googleapis.com/v0/b/dawgo-63d5f.appspot.com/o/itemImages%2FQ6wgjfSGBN6Lbsad%2Fairpods.jpeg?alt=media&token=72ec12b1-4e95-4d0e-bc20-30e85299a5a3",
    ],
    itemId: "-My0Q6wgjfSGBN6Lbsad",
    location: "1111",
    negotiable: true,
    pickUp: true,
    price: "99",
    title: "Airpods",
    userId: "wYnWRFYrm1UZVTxTRs5M1NhP0Vd2",
    savedBy: ["eN9yXV0gS8deCTlNvNNLJyOjXuJ2"],
  },
};
export const USER = {
  wYnWRFYrm1UZVTxTRs5M1NhP0Vd21: {
    userId: "wYnWRFYrm1UZVTxTRs5M1NhP0Vd21",
    name: "Jack",
    description: "Hi, I am Jack",
    UW: true,
    zipCode: 98105,
    imgUrl: null,
    contacts: {
      phone: 7890,
      email: "bbb@uw.edu",
    },
  },
  eN9yXV0gS8deCTlNvNNLJyOjXuJ2: {
    userId: "eN9yXV0gS8deCTlNvNNLJyOjXuJ2",
    name: "Patrick",
    description: "I am a student at UW",
    UW: true,
    zipCode: 98105,
    imgUrl: "./img/portrait-man.png",
    contacts: {
      weChat: 1234,
      phone: 7890,
      email: "583482035@qq.com",
      instagram: "yunqian.cheng",
    },
  },
};

export const DEFAULT_USER_INFO = {
  name: "Default User",
  UW: false,
  zipCode: 98105,
  userId: "defaultId",
  description: "Hi, I am a default user, a random guy.",
  imgUrl: "./img/default_user_profile.jpg",
  contacts: "123456",
};

export const DEFAULT_ITEM = {
  category: "Other",
  condition: "Brand new",
  description: "There is nothing on this page",
  dropOff: false,
  imgUrls: ["./img/missing_image.jpg"],
  itemId: "default_id",
  location: "98105",
  negotiable: false,
  pickUp: true,
  price: "0",
  title: "Default Item",
  userId: "defaultId",
  savedBy: [],
};
